export const images = [


    {
        title: 'React Summit',
        description: 'React Summit is the largest React conference worldwide, uniting thousands of Front-end and Full-stack engineers from around the world. The conference provides a platform for developers to learn the latest trends and innovations in the React ecosystem, from building performant applications to mastering advanced patterns and practices.',
        location: 'Amsterdam, Netherlands',
        date: '2021-08-21',
        time: '09:00',
        image: 'https://picsum.photos/200/300',
        link: 'https://reactsummit.com',
        tags: 'react,frontend,conference',
        category: 'conference',
        published_at: '2021-05-01',
        status: 'active',
        id: 2,
    },
    {
        title: 'Vue.js Amsterdam',
        description: 'Vue.js Amsterdam is the largest Vue conference in the world, bringing together Vue.js enthusiasts and developers to share knowledge and experience. Attendees will learn from industry experts about the latest advancements in Vue.js, including best practices, state management, and Vue 3 features.',
        location: 'Amsterdam, Netherlands',
        date: '2021-11-01',
        time: '10:00',
        image: 'https://picsum.photos/200/300',
        link: 'https://vuejs.amsterdam',
        tags: 'vuejs,javascript,frontend',
        category: 'conference',
        published_at: '2021-08-01',
        status: 'active',
        id: 3,
    },
    {
        title: 'Svelte Summit',
        description: 'Svelte Summit is a conference dedicated to the Svelte framework, offering a unique opportunity for developers to dive deep into Svelte and Sapper. The event features talks from core team members and industry experts, covering topics like SvelteKit, transitions, and optimizing performance.',
        location: 'Stockholm, Sweden',
        date: '2021-09-15',
        time: '11:00',
        image: 'https://picsum.photos/200/300',
        link: 'https://sveltesummit.com',
        tags: 'svelte,frontend,javascript',
        category: 'conference',
        published_at: '2021-06-15',
        status: 'active',
        id: 4,
    },
    {
        title: 'Next.js Conf',
        description: 'Next.js Conf is a global conference that brings together developers from around the world to learn about the latest features and improvements in the Next.js framework. The conference includes sessions on server-side rendering, static site generation, and integrating with various data sources.',
        location: 'Online',
        date: '2021-10-25',
        time: '13:00',
        image: 'https://picsum.photos/200/300',
        link: 'https://nextjs.org/conf',
        tags: 'nextjs,react,server-side-rendering',
        category: 'conference',
        published_at: '2021-07-25',
        status: 'active',
        id: 5,
    },
    {
        title: 'JavaScript Interactive',
        description: 'JavaScript Interactive is a comprehensive workshop series aimed at developers who want to deepen their understanding of modern JavaScript. The workshops cover a wide range of topics, including ES6+, asynchronous programming, and JavaScript frameworks.',
        location: 'San Francisco, USA',
        date: '2021-12-10',
        time: '09:30',
        image: 'https://picsum.photos/200/300',
        link: 'https://javascriptinteractive.com',
        tags: 'javascript,workshop,es6',
        category: 'workshop',
        published_at: '2021-09-10',
        status: 'active',
        id: 6,
    },
    {
        title: 'Angular Connect',
        description: 'Angular Connect is the premier conference for Angular developers, offering in-depth talks, hands-on sessions, and networking opportunities with industry experts. The conference covers a wide range of Angular topics, including Angular Ivy, component design patterns, and performance optimization.',
        location: 'London, UK',
        date: '2021-10-18',
        time: '09:00',
        image: 'https://picsum.photos/200/300',
        link: 'https://angularconnect.com',
        tags: 'angular,typescript,frontend',
        category: 'conference',
        published_at: '2021-07-18',
        status: 'active',
        id: 7,
    }
];
